[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
health = "73bramYkSneHzsVxX3ovY6anDYgcRsnthqi4d4Htsskc"
http = "7VRgExw4zFKwqfu9xTnYgfmzUdYUDcFwcy9HiiYJFwPB"
network = "Fady3DhXdLAuVZgu9t8SQALsff9hSF9YDNRMxtW6iR1Z"
pool = "4GMkkUAvDQRsoVVLzcKHoJatP82m1o6Jk4g1gG8UxSqh"
scheduler = "4SnjAUTwNaxT2VTmT7m4doDofVei1cudKb9EiLdxYzej"

[programs.testnet]
health = "73bramYkSneHzsVxX3ovY6anDYgcRsnthqi4d4Htsskc"
http = "7VRgExw4zFKwqfu9xTnYgfmzUdYUDcFwcy9HiiYJFwPB"
network = "Fady3DhXdLAuVZgu9t8SQALsff9hSF9YDNRMxtW6iR1Z"
pool = "4GMkkUAvDQRsoVVLzcKHoJatP82m1o6Jk4g1gG8UxSqh"
scheduler = "4SnjAUTwNaxT2VTmT7m4doDofVei1cudKb9EiLdxYzej"

[programs.mainnet]
health = "73bramYkSneHzsVxX3ovY6anDYgcRsnthqi4d4Htsskc"
http = "7VRgExw4zFKwqfu9xTnYgfmzUdYUDcFwcy9HiiYJFwPB"
network = "Fady3DhXdLAuVZgu9t8SQALsff9hSF9YDNRMxtW6iR1Z"
pool = "4GMkkUAvDQRsoVVLzcKHoJatP82m1o6Jk4g1gG8UxSqh"
scheduler = "4SnjAUTwNaxT2VTmT7m4doDofVei1cudKb9EiLdxYzej"

[registry]
url = "https://anchor.projectserum.com"
