[package]
name = "cronos-bot"
version = "0.1.0"
edition = "2021"
description = "Worker bot to execute Cronos tasks"
license = "Apache-2.0"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/bot"
documentation = "https://docs.cronos.so"
readme = "./README.md"
keywords = ["solana", "cronos", "program"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.20.1"
cached = { version = "0.30.0", features = ["async", "proc_macro"] }
cronos-sdk = "0.1.0"
dotenv = "0.15.0"
postgres = "0.19.2"
solana-account-decoder = "1.9.5"
solana-client = "1.9.5"
solana-client-helpers = "1.1.0"
solana-sdk = "1.9.5"
ttl_cache = "0.5.1"
