[package]
name = "clockwork-cli"
version = "2.0.2"
description = "Command line interface for Clockwork"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://clockwork.xyz"
repository = "https://github.com/clockwork-xyz/cli"
documentation = "https://docs.clockwork.xyz"
readme = "./README.md"
keywords = ["solana"]

[dependencies]
anchor-lang = "0.26.0"
anyhow = "1.0.61"
bincode = "1.3.3"
clap = { version = "3.1.2", features = ["derive"] }
clockwork-client = { path = "../client", version = "2.0.2" }
clockwork-cron = { path = "../cron", version = "2.0.0-alpha" }
clockwork-relayer-api = { path = "../relayer/api", version = "2.0.1" }
clockwork-utils = { path = "../utils", version = "2.0.2" }
clockwork-webhook-program = { path = "../programs/webhook", version = "2.0.1" }
chrono = { version = "0.4.19", default-features = false, features = ["alloc"] }
dirs-next = "2.0.0"
regex = "1.6.0"
reqwest = "0.11.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_yaml = "0.9.4"
solana-account-decoder = "~1.14.15"
solana-client = "~1.14.15"
solana-clap-utils = "~1.14.15"
solana-cli-config = "~1.14.15"
solana-sdk = "~1.14.15"
spl-associated-token-account = "1.1.1"
spl-memo = "3.0.1"
spl-token = "~3.5.0"
thiserror = "1.0.30"
version = "3.0.0"

[[bin]]
name = "clockwork"
path = "src/main.rs"

[build-dependencies]
cargo_toml = "0.13.0"
regex = "1.6.0"
